# Generated by Django 5.0.1 on 2024-01-23 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professionnelsante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=255)),
                ('code_patient', models.CharField(max_length=50, null=True)),
                ('sexe', models.CharField(max_length=50)),
                ('date_naissance', models.DateTimeField(auto_now_add=True)),
                ('numero_mobile', models.IntegerField(max_length=14)),
                ('numero_telephone', models.IntegerField(null=True)),
                ('residence_habituelle', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('religion', models.CharField(null=True)),
                ('profession', models.CharField(null=True)),
                ('residence_actuelle', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('pere', models.CharField(max_length=100, null=True)),
                ('mere', models.CharField(max_length=100, null=True)),
                ('autre_ethnie', models.CharField(max_length=100, null=True)),
                ('Professionnelsante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centresante.professionnelsante', unique=True)),
            ],
        ),
    ]
