# Generated by Django 5.0.1 on 2024-01-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centresante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='autre_ethnie',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='code_patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mere',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='numero_telephone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pere',
        ),
        migrations.AlterField(
            model_name='patient',
            name='Professionnelsante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Patient', to='centresante.professionnelsante'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numero_mobile',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='professionnelsante',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
